baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Demo for Hugo'

theme = 'anatole-master'

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule

[params]
title = "Kafka Engdoc"
author = "By Team Messaging Platform"
description = "Kafka Documentation Page"
profilePicture = "/images/Bellingham.jpg"
readMore = true
#contactFormAction = "https://formspree.io/f/your-form-hash-here"

[author]
  name = "Linh"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Pinned"
  weight = 150
  identifier = "pinned"
  url = "/series/"

  [[menu.main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"
