baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Demo for Hugo'

theme = 'anatole'

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule

[params]
title = "Kafka Engdoc"
author = "By Team Messaging Platform"
description = "Kafka Documentation Page"
profilePicture = "/images/Bellingham.jpg"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80


